#!/bin/bash
# sign-fit.sh — Sign a FIT image in-place using keys from keys/ and optionally
#               embed the public certificate into the U-Boot DTB so U-Boot can
#               verify the image at runtime.
#
# Usage: ./scripts/sign-fit.sh [image.itb] [key-name]
#   image.itb  — FIT image to sign  (default: build/boot.itb)
#   key-name   — key prefix in keys/ (default: dev)
#
# Run ./scripts/make-demo-fit.sh first if build/boot.itb does not exist yet.
# Requires: u-boot-tools (mkimage), keys generated by ./scripts/gen-keys.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/check-deps.sh
# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/check-deps.sh"

ITB="${1:-build/boot.itb}"
KEY_NAME="${2:-dev}"
KEYS_DIR="${REPO_ROOT}/keys"
DTB="${REPO_ROOT}/u-boot/u-boot.dtb"

check_deps mkimage || exit 1
echo ""

if [ ! -f "$ITB" ]; then
    log_error "FIT image not found: ${ITB}"
    log_info  "Run ./scripts/make-demo-fit.sh to create one, then retry."
    exit 1
fi

if [ ! -f "${KEYS_DIR}/${KEY_NAME}.key" ]; then
    log_error "Signing key not found: ${KEYS_DIR}/${KEY_NAME}.key"
    log_info  "Run ./scripts/gen-keys.sh ${KEY_NAME} first."
    exit 1
fi

EMBED_DTB=0
if [ -f "$DTB" ]; then
    EMBED_DTB=1
else
    log_warn "U-Boot DTB not found at ${DTB}."
    log_warn "Run ./build.sh first to enable public key embedding into the DTB."
fi

log_info "Signing FIT image: ${ITB}  (key: ${KEY_NAME})"

if [ "$EMBED_DTB" -eq 1 ]; then
    log_info "Embedding public certificate into DTB: ${DTB}"
    mkimage -F -k "$KEYS_DIR" -K "$DTB" -r "$ITB"
else
    mkimage -F -k "$KEYS_DIR" -r "$ITB"
fi

echo ""
log_ok "FIT image signed: ${ITB}"
echo ""
log_info "Image contents:"
mkimage -l "$ITB"
echo ""

if [ "$EMBED_DTB" -eq 1 ]; then
    log_info "Public key embedded in DTB. Rebuild U-Boot to bake it into the ROM:"
    log_info "  ./build.sh"
fi

log_ok "Done. U-Boot will verify this image against the embedded certificate at boot time."
